name: http
version: 0.11.3+3
author: "Dart Team <misc@dartlang.org>"
homepage: https://github.com/dart-lang/http
description: A composable, Future-based API for making HTTP requests.
dependencies:
  http_parser: ">=0.0.1 <3.0.0"
  path: ">=0.9.0 <2.0.0"
  stack_trace: ">=0.9.1 <2.0.0"
dev_dependencies:
  test: ">=0.12.0 <0.13.0"
environment:
  sdk: ">=1.9.0 <2.0.0"
