name: cupertino_http
version: 1.5.0-wip
description: >-
  A macOS/iOS Flutter plugin that provides access to the Foundation URL
  Loading System.
repository: https://github.com/dart-lang/http/tree/master/pkgs/cupertino_http
publish_to: none

environment:
  sdk: ^3.2.0  # XXX Wrong!
  flutter: '>=3.16.0'  # XXX Wrong!

dependencies:
  async: ^2.5.0
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  http: ^1.2.0
  http_profile:
    path: ../http_profile
  web_socket:
    path: ../web_socket

dev_dependencies:
  dart_flutter_team_lints: ^2.0.0
  ffigen: ^9.0.1

flutter:
  plugin:
    platforms:
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true
