name: web_socket_conformance_tests
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.2.4

# Add regular dependencies here.
dependencies:
  async: ^2.11.0
  dart_style: ^2.3.4
  stream_channel: ^2.1.2
  test: ^1.24.0
  websocket:
    path: ../websocket
dev_dependencies:
  lints: ^2.1.0
