name: cronet_http
description: A new Flutter plugin project.
version: 0.0.1

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  pigeon: ^3.2.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.cronet_http
        pluginClass: CronetHttpPlugin
