sdk:
  - stable

stages:
  - analyze_and_format:
      - analyze: --fatal-infos
      - format:
  - unit_test:
      - test: --platform linux
      - test: --platform chrome
      - command: flutter test
