sdk:
- pubspec
- dev

stages:
- analyze_and_format:
  - analyze: --fatal-infos
  - format:
    sdk:
    - dev
- unit_test:
  - test: --platform vm
  - test: --platform chrome
  - command: flutter test
