sdk:
- pubspec
- dev

stages:
- analyze_and_format:
  - analyze: --fatal-infos
  - format:
    sdk:
    - dev
- unit_test:
  - test: --test-randomize-ordering-seed=random -p vm
  - test: --test-randomize-ordering-seed=random -p chrome -c dart2js
  - test: --test-randomize-ordering-seed=random -p chrome -c dart2wasm
